### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Taki7o7** [ashumkin/Chrome-passwords#1]
Hey could you comment in english?  I can't read russian crypto language ^^

and good job, i love it :)

**Comment by ashumkin** [comment]
I'm sorry.
JFYI, I'm not the author. The author (he wrote the article linked in README) put on Dropbox the source code as a ZIP file. I've just copied the latter as a project on Github.
Maybe I'll translate the comments to English later. Then I'll close the issue.
